package com.maerdngaminng.ts3.queryapi.rmo;

public enum CreateChannelProperty {
	CHANNEL_TOPIC,
	CHANNEL_DESCRIPTION,
	CHANNEL_PASSWORD,
	CHANNEL_CODEC,
	CHANNEL_CODEC_QUALITY,
	CHANNEL_MAXCLIENTS,
	CHANNEL_MAXFAMILYCLIENTS,
	CHANNEL_ORDER,
	CHANNEL_FLAG_PERMANENT,
	CHANNEL_FLAG_SEMI_PERMANENT,
	CHANNEL_FLAG_TEMPORARY,
	CHANNEL_FLAG_DEFAULT,
	CHANNEL_FLAG_MAXCLIENTS_UNLIMITED,
	CHANNEL_FLAG_MAXFAMILYCLIENTS_UNLIMITED,
	CHANNEL_FLAG_MAXFAMILYCLIENTS_INHERITED,
	CHANNEL_NEEDED_TALK_POWER,
	CHANNEL_NAME_PHONETIC,
	CHANNEL_ICON_ID,
	CHANNEL_CODEC_IS_UNENCRYPTED,
	CPID
}
